/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates.$templateId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as DocsDocIdRouteImport } from './routes/docs.$docId'
import { Route as AuthUploadRouteImport } from './routes/_auth.upload'
import { Route as AuthTemplatesRouteImport } from './routes/_auth.templates'
import { Route as AuthSharedRouteImport } from './routes/_auth.shared'
import { Route as AuthSettingsRouteImport } from './routes/_auth.settings'
import { Route as AuthNotificationsRouteImport } from './routes/_auth.notifications'
import { Route as AuthDocsRouteImport } from './routes/_auth.docs'
import { Route as AuthCampaignsRouteImport } from './routes/_auth.campaigns'
import { Route as AuthActivityRouteImport } from './routes/_auth.activity'
import { Route as DocsDocIdCompleteRouteImport } from './routes/docs.$docId_.complete'
import { Route as AuthSettingsTabRouteImport } from './routes/_auth.settings.$tab'
import { Route as AuthCampaignsNewRouteImport } from './routes/_auth.campaigns.new'
import { Route as AuthCampaignsCampaignIdRouteImport } from './routes/_auth.campaigns.$campaignId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDocIdRoute = DocsDocIdRouteImport.update({
  id: '/docs/$docId',
  path: '/docs/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUploadRoute = AuthUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTemplatesRoute = AuthTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSharedRoute = AuthSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNotificationsRoute = AuthNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDocsRoute = AuthDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCampaignsRoute = AuthCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthRoute,
} as any)
const AuthActivityRoute = AuthActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthRoute,
} as any)
const DocsDocIdCompleteRoute = DocsDocIdCompleteRouteImport.update({
  id: '/docs/$docId_/complete',
  path: '/docs/$docId/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsTabRoute = AuthSettingsTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthCampaignsNewRoute = AuthCampaignsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthCampaignsRoute,
} as any)
const AuthCampaignsCampaignIdRoute = AuthCampaignsCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => AuthCampaignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/activity': typeof AuthActivityRoute
  '/campaigns': typeof AuthCampaignsRouteWithChildren
  '/docs': typeof AuthDocsRoute
  '/notifications': typeof AuthNotificationsRoute
  '/settings': typeof AuthSettingsRouteWithChildren
  '/shared': typeof AuthSharedRoute
  '/templates': typeof AuthTemplatesRoute
  '/upload': typeof AuthUploadRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/campaigns/$campaignId': typeof AuthCampaignsCampaignIdRoute
  '/campaigns/new': typeof AuthCampaignsNewRoute
  '/settings/$tab': typeof AuthSettingsTabRoute
  '/docs/$docId/complete': typeof DocsDocIdCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/activity': typeof AuthActivityRoute
  '/campaigns': typeof AuthCampaignsRouteWithChildren
  '/docs': typeof AuthDocsRoute
  '/notifications': typeof AuthNotificationsRoute
  '/settings': typeof AuthSettingsRouteWithChildren
  '/shared': typeof AuthSharedRoute
  '/templates': typeof AuthTemplatesRoute
  '/upload': typeof AuthUploadRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/campaigns/$campaignId': typeof AuthCampaignsCampaignIdRoute
  '/campaigns/new': typeof AuthCampaignsNewRoute
  '/settings/$tab': typeof AuthSettingsTabRoute
  '/docs/$docId/complete': typeof DocsDocIdCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/_auth/activity': typeof AuthActivityRoute
  '/_auth/campaigns': typeof AuthCampaignsRouteWithChildren
  '/_auth/docs': typeof AuthDocsRoute
  '/_auth/notifications': typeof AuthNotificationsRoute
  '/_auth/settings': typeof AuthSettingsRouteWithChildren
  '/_auth/shared': typeof AuthSharedRoute
  '/_auth/templates': typeof AuthTemplatesRoute
  '/_auth/upload': typeof AuthUploadRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/_auth/campaigns/$campaignId': typeof AuthCampaignsCampaignIdRoute
  '/_auth/campaigns/new': typeof AuthCampaignsNewRoute
  '/_auth/settings/$tab': typeof AuthSettingsTabRoute
  '/docs/$docId_/complete': typeof DocsDocIdCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guide'
    | '/login'
    | '/activity'
    | '/campaigns'
    | '/docs'
    | '/notifications'
    | '/settings'
    | '/shared'
    | '/templates'
    | '/upload'
    | '/docs/$docId'
    | '/invite/$token'
    | '/templates/$templateId'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/settings/$tab'
    | '/docs/$docId/complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guide'
    | '/login'
    | '/activity'
    | '/campaigns'
    | '/docs'
    | '/notifications'
    | '/settings'
    | '/shared'
    | '/templates'
    | '/upload'
    | '/docs/$docId'
    | '/invite/$token'
    | '/templates/$templateId'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/settings/$tab'
    | '/docs/$docId/complete'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/guide'
    | '/login'
    | '/_auth/activity'
    | '/_auth/campaigns'
    | '/_auth/docs'
    | '/_auth/notifications'
    | '/_auth/settings'
    | '/_auth/shared'
    | '/_auth/templates'
    | '/_auth/upload'
    | '/docs/$docId'
    | '/invite/$token'
    | '/templates/$templateId'
    | '/_auth/campaigns/$campaignId'
    | '/_auth/campaigns/new'
    | '/_auth/settings/$tab'
    | '/docs/$docId_/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  GuideRoute: typeof GuideRoute
  LoginRoute: typeof LoginRoute
  DocsDocIdRoute: typeof DocsDocIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  DocsDocIdCompleteRoute: typeof DocsDocIdCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$docId': {
      id: '/docs/$docId'
      path: '/docs/$docId'
      fullPath: '/docs/$docId'
      preLoaderRoute: typeof DocsDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/upload': {
      id: '/_auth/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthUploadRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/templates': {
      id: '/_auth/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthTemplatesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/shared': {
      id: '/_auth/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof AuthSharedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/notifications': {
      id: '/_auth/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthNotificationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/docs': {
      id: '/_auth/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthDocsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/campaigns': {
      id: '/_auth/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthCampaignsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/activity': {
      id: '/_auth/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthActivityRouteImport
      parentRoute: typeof AuthRoute
    }
    '/docs/$docId_/complete': {
      id: '/docs/$docId_/complete'
      path: '/docs/$docId/complete'
      fullPath: '/docs/$docId/complete'
      preLoaderRoute: typeof DocsDocIdCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings/$tab': {
      id: '/_auth/settings/$tab'
      path: '/$tab'
      fullPath: '/settings/$tab'
      preLoaderRoute: typeof AuthSettingsTabRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/campaigns/new': {
      id: '/_auth/campaigns/new'
      path: '/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AuthCampaignsNewRouteImport
      parentRoute: typeof AuthCampaignsRoute
    }
    '/_auth/campaigns/$campaignId': {
      id: '/_auth/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof AuthCampaignsCampaignIdRouteImport
      parentRoute: typeof AuthCampaignsRoute
    }
  }
}

interface AuthCampaignsRouteChildren {
  AuthCampaignsCampaignIdRoute: typeof AuthCampaignsCampaignIdRoute
  AuthCampaignsNewRoute: typeof AuthCampaignsNewRoute
}

const AuthCampaignsRouteChildren: AuthCampaignsRouteChildren = {
  AuthCampaignsCampaignIdRoute: AuthCampaignsCampaignIdRoute,
  AuthCampaignsNewRoute: AuthCampaignsNewRoute,
}

const AuthCampaignsRouteWithChildren = AuthCampaignsRoute._addFileChildren(
  AuthCampaignsRouteChildren,
)

interface AuthSettingsRouteChildren {
  AuthSettingsTabRoute: typeof AuthSettingsTabRoute
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
  AuthSettingsTabRoute: AuthSettingsTabRoute,
}

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
  AuthSettingsRouteChildren,
)

interface AuthRouteChildren {
  AuthActivityRoute: typeof AuthActivityRoute
  AuthCampaignsRoute: typeof AuthCampaignsRouteWithChildren
  AuthDocsRoute: typeof AuthDocsRoute
  AuthNotificationsRoute: typeof AuthNotificationsRoute
  AuthSettingsRoute: typeof AuthSettingsRouteWithChildren
  AuthSharedRoute: typeof AuthSharedRoute
  AuthTemplatesRoute: typeof AuthTemplatesRoute
  AuthUploadRoute: typeof AuthUploadRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthActivityRoute: AuthActivityRoute,
  AuthCampaignsRoute: AuthCampaignsRouteWithChildren,
  AuthDocsRoute: AuthDocsRoute,
  AuthNotificationsRoute: AuthNotificationsRoute,
  AuthSettingsRoute: AuthSettingsRouteWithChildren,
  AuthSharedRoute: AuthSharedRoute,
  AuthTemplatesRoute: AuthTemplatesRoute,
  AuthUploadRoute: AuthUploadRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  GuideRoute: GuideRoute,
  LoginRoute: LoginRoute,
  DocsDocIdRoute: DocsDocIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  DocsDocIdCompleteRoute: DocsDocIdCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
